theme: jekyll-theme-minimal
title: TSchultz922's homepage
description: Bookmark this to keep an eye on my project updates!

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      mermaid:
        tag: "<script type='module' src='https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs'></script>"
